package photoman.service.nef.lookup;

public class IFDLookup extends Lookup
{

	public static final String IFD_INTEROP_INDEX = "InteropIndex";
	public static final String IFD_INTEROP_VERSION = "InteropVersion";
	public static final String IFD_PROCESSING_SOFTWARE = "ProcessingSoftware";
	public static final String IFD_SUBFILE_TYPE = "SubfileType";
	public static final String IFD_OLD_SUBFILE_TYPE = "OldSubfileType";
	public static final String IFD_IMAGE_WIDTH = "ImageWidth";
	public static final String IFD_IMAGE_HEIGHT = "ImageHeight";
	public static final String IFD_BITS_PER_SAMPLE = "BitsPerSample";
	public static final String IFD_COMPRESSION = "Compression";
	public static final String IFD_PHOTOMETRIC_INTERPRETATION = "PhotometricInterpretation";
	public static final String IFD_THRESHOLDING = "Thresholding";
	public static final String IFD_CELL_WIDTH = "CellWidth";
	public static final String IFD_CELL_LENGTH = "CellLength";
	public static final String IFD_FILL_ORDER = "FillOrder";
	public static final String IFD_DOCUMENT_NAME = "DocumentName";
	public static final String IFD_IMAGE_DESCRIPTION = "ImageDescription";
	public static final String IFD_MAKE = "Make";
	public static final String IFD_MODEL = "Model";
	public static final String IFD_STRIP_OFFSETS = "StripOffsets";
	public static final String IFD_ORIENTATION = "Orientation";
	public static final String IFD_SAMPLES_PER_PIXEL = "SamplesPerPixel";
	public static final String IFD_ROWS_PER_STRIP = "RowsPerStrip";
	public static final String IFD_STRIP_BYTE_COUNTS = "StripByteCounts";
	public static final String IFD_MIN_SAMPLE_VALUE = "MinSampleValue";
	public static final String IFD_MAX_SAMPLE_VALUE = "MaxSampleValue";
	public static final String IFD_X_RESOLUTION = "XResolution";
	public static final String IFD_Y_RESOLUTION = "YResolution";
	public static final String IFD_PLANAR_CONFIGURATION = "PlanarConfiguration";
	public static final String IFD_PAGE_NAME = "PageName";
	public static final String IFD_X_POSITION = "XPosition";
	public static final String IFD_Y_POSITION = "YPosition";
	public static final String IFD_FREE_OFFSETS = "FreeOffsets";
	public static final String IFD_FREE_BYTE_COUNTS = "FreeByteCounts";
	public static final String IFD_GRAY_RESPONSE_UNIT = "GrayResponseUnit";
	public static final String IFD_GRAY_RESPONSE_CURVE = "GrayResponseCurve";
	public static final String IFD_T4_OPTIONS = "T4Options";
	public static final String IFD_T6_OPTIONS = "T6Options";
	public static final String IFD_RESOLUTION_UNIT = "ResolutionUnit";
	public static final String IFD_PAGE_NUMBER = "PageNumber";
	public static final String IFD_COLOR_RESPONSE_UNIT = "ColorResponseUnit";
	public static final String IFD_TRANSFER_FUNCTION = "TransferFunction";
	public static final String IFD_SOFTWARE = "Software";
	public static final String IFD_MODIFY_DATE = "ModifyDate";
	public static final String IFD_ARTIST = "Artist";
	public static final String IFD_HOST_COMPUTER = "HostComputer";
	public static final String IFD_PREDICTOR = "Predictor";
	public static final String IFD_WHITE_POINT = "WhitePoint";
	public static final String IFD_PRIMARY_CHROMATICITIES = "PrimaryChromaticities";
	public static final String IFD_COLOR_MAP = "ColorMap";
	public static final String IFD_HALFTONE_HINTS = "HalftoneHints";
	public static final String IFD_TILE_WIDTH = "TileWidth";
	public static final String IFD_TILE_LENGTH = "TileLength";
	public static final String IFD_TILE_OFFSETS = "TileOffsets";
	public static final String IFD_TILE_BYTE_COUNTS = "TileByteCounts";
	public static final String IFD_BAD_FAX_LINES = "BadFaxLines";
	public static final String IFD_CLEAN_FAX_DATA = "CleanFaxData";
	public static final String IFD_CONSECUTIVE_BAD_FAX_LINES = "ConsecutiveBadFaxLines";
	public static final String IFD_SUB_IFD = "SubIFD";
	public static final String IFD_INK_SET = "InkSet";
	public static final String IFD_INK_NAMES = "InkNames";
	public static final String IFD_NUMBEROF_INKS = "NumberofInks";
	public static final String IFD_DOT_RANGE = "DotRange";
	public static final String IFD_TARGET_PRINTER = "TargetPrinter";
	public static final String IFD_EXTRA_SAMPLES = "ExtraSamples";
	public static final String IFD_SAMPLE_FORMAT = "SampleFormat";
	public static final String IFD_S_MIN_SAMPLE_VALUE = "SMinSampleValue";
	public static final String IFD_S_MAX_SAMPLE_VALUE = "SMaxSampleValue";
	public static final String IFD_TRANSFER_RANGE = "TransferRange";
	public static final String IFD_CLIP_PATH = "ClipPath";
	public static final String IFD_X_CLIP_PATH_UNITS = "XClipPathUnits";
	public static final String IFD_Y_CLIP_PATH_UNITS = "YClipPathUnits";
	public static final String IFD_INDEXED = "Indexed";
	public static final String IFD_JPEG_TABLES = "JPEGTables";
	public static final String IFD_OPI_PROXY = "OPIProxy";
	public static final String IFD_GLOBAL_PARAMETERS_I_F_D = "GlobalParametersIFD";
	public static final String IFD_PROFILE_TYPE = "ProfileType";
	public static final String IFD_FAX_PROFILE = "FaxProfile";
	public static final String IFD_CODING_METHODS = "CodingMethods";
	public static final String IFD_VERSION_YEAR = "VersionYear";
	public static final String IFD_MODE_NUMBER = "ModeNumber";
	public static final String IFD_DECODE = "Decode";
	public static final String IFD_DEFAULT_IMAGE_COLOR = "DefaultImageColor";
	public static final String IFD_T82_OPTIONS = "T82Options";
	public static final String IFD_JPEG_PROC = "JPEGProc";
	public static final String IFD_THUMBNAIL_OFFSET = "ThumbnailOffset";
	public static final String IFD_THUMBNAIL_LENGTH = "ThumbnailLength";
	public static final String IFD_JPEG_RESTART_INTERVAL = "JPEGRestartInterval";
	public static final String IFD_JPEG_LOSSLESS_PREDICTORS = "JPEGLosslessPredictors";
	public static final String IFD_JPEG_POINT_TRANSFORMS = "JPEGPointTransforms";
	public static final String IFD_JPEG_Q_TABLES = "JPEGQTables";
	public static final String IFD_JPEG_DC_TABLES = "JPEGDCTables";
	public static final String IFD_JPEG_AC_TABLES = "JPEGACTables";
	public static final String IFD_YCBCR_COEFFICIENTS = "YCbCrCoefficients";
	public static final String IFD_YCBCR_SUB_SAMPLING = "YCbCrSubSampling";
	public static final String IFD_YCBCR_POSITIONING = "YCbCrPositioning";
	public static final String IFD_REFERENCE_BLACK_WHITE = "ReferenceBlackWhite";
	public static final String IFD_STRIP_ROW_COUNTS = "StripRowCounts";
	public static final String IFD_APPLICATION_NOTES = "ApplicationNotes";
	public static final String IFD_USP_TO_MISCELLANEOUS = "USPTOMiscellaneous";
	public static final String IFD_RELATED_IMAGE_FILE_FORMAT = "RelatedImageFileFormat";
	public static final String IFD_RELATED_IMAGE_WIDTH = "RelatedImageWidth";
	public static final String IFD_RELATED_IMAGE_HEIGHT = "RelatedImageHeight";
	public static final String IFD_RATING = "Rating";
	public static final String IFD_XP_DIP_XML = "XP_DIP_XML";
	public static final String IFD_STITCH_INFO = "StitchInfo";
	public static final String IFD_RATING_PERCENT = "RatingPercent";
	public static final String IFD_SONY_RAW_FILE_TYPE = "SonyRawFileType";
	public static final String IFD_CHROMATIC_ABERRATION_CORR_PARAMS = "ChromaticAberrationCorrParams";
	public static final String IFD_DISTORTION_CORR_PARAMS = "DistortionCorrParams";
	public static final String IFD_IMAGE_ID = "ImageID";
	public static final String IFD_WANG_TAG1 = "WangTag1";
	public static final String IFD_WANG_ANNOTATION = "WangAnnotation";
	public static final String IFD_WANG_TAG3 = "WangTag3";
	public static final String IFD_WANG_TAG4 = "WangTag4";
	public static final String IFD_IMAGE_REFERENCE_POINTS = "ImageReferencePoints";
	public static final String IFD_REGION_XFORM_TACK_POINT = "RegionXformTackPoint";
	public static final String IFD_WARP_QUADRILATERAL = "WarpQuadrilateral";
	public static final String IFD_AFFINE_TRANSFORM_MAT = "AffineTransformMat";
	public static final String IFD_MATTEING = "Matteing";
	public static final String IFD_DATA_TYPE = "DataType";
	public static final String IFD_IMAGE_DEPTH = "ImageDepth";
	public static final String IFD_TILE_DEPTH = "TileDepth";
	public static final String IFD_IMAGE_FULL_WIDTH = "ImageFullWidth";
	public static final String IFD_IMAGE_FULL_HEIGHT = "ImageFullHeight";
	public static final String IFD_TEXTURE_FORMAT = "TextureFormat";
	public static final String IFD_WRAP_MODES = "WrapModes";
	public static final String IFD_FOV_COT = "FovCot";
	public static final String IFD_MATRIX_WORLD_TO_SCREEN = "MatrixWorldToScreen";
	public static final String IFD_MATRIX_WORLD_TO_CAMERA = "MatrixWorldToCamera";
	public static final String IFD_MODEL2 = "Model2";
	public static final String IFD_CFA_REPEAT_PATTERN_DIM = "CFARepeatPatternDim";
	public static final String IFD_CFA_PATTERN2 = "CFAPattern2";
	public static final String IFD_BATTERY_LEVEL = "BatteryLevel";
	public static final String IFD_KODAK_I_F_D = "KodakIFD";
	public static final String IFD_COPYRIGHT = "Copyright";
	public static final String IFD_EXPOSURE_TIME = "ExposureTime";
	public static final String IFD_FNUMBER = "FNumber";
	public static final String IFD_MD_FILE_TAG = "MDFileTag";
	public static final String IFD_MD_SCALE_PIXEL = "MDScalePixel";
	public static final String IFD_MD_COLOR_TABLE = "MDColorTable";
	public static final String IFD_MD_LAB_NAME = "MDLabName";
	public static final String IFD_MD_SAMPLE_INFO = "MDSampleInfo";
	public static final String IFD_MD_PREP_DATE = "MDPrepDate";
	public static final String IFD_MD_PREP_TIME = "MDPrepTime";
	public static final String IFD_MD_FILE_UNITS = "MDFileUnits";
	public static final String IFD_PIXEL_SCALE = "PixelScale";
	public static final String IFD_ADVENT_SCALE = "AdventScale";
	public static final String IFD_ADVENT_REVISION = "AdventRevision";
	public static final String IFD_UIC1_TAG = "UIC1Tag";
	public static final String IFD_UIC2_TAG = "UIC2Tag";
	public static final String IFD_UIC3_TAG = "UIC3Tag";
	public static final String IFD_UIC4_TAG = "UIC4Tag";
	public static final String IFD_IPTC_NAA = "IPTC-NAA";
	public static final String IFD_INTERGRAPH_PACKET_DATA = "IntergraphPacketData";
	public static final String IFD_INTERGRAPH_FLAG_REGISTERS = "IntergraphFlagRegisters";
	public static final String IFD_INTERGRAPH_MATRIX = "IntergraphMatrix";
	public static final String IFD_INGR_RESERVED = "INGRReserved";
	public static final String IFD_MODEL_TIE_POINT = "ModelTiePoint";
	public static final String IFD_SITE = "Site";
	public static final String IFD_COLOR_SEQUENCE = "ColorSequence";
	public static final String IFD_IT8_HEADER = "IT8Header";
	public static final String IFD_RASTER_PADDING = "RasterPadding";
	public static final String IFD_BITS_PER_RUN_LENGTH = "BitsPerRunLength";
	public static final String IFD_BITS_PER_EXTENDED_RUN_LENGTH = "BitsPerExtendedRunLength";
	public static final String IFD_COLOR_TABLE = "ColorTable";
	public static final String IFD_IMAGE_COLOR_INDICATOR = "ImageColorIndicator";
	public static final String IFD_BACKGROUND_COLOR_INDICATOR = "BackgroundColorIndicator";
	public static final String IFD_IMAGE_COLOR_VALUE = "ImageColorValue";
	public static final String IFD_BACKGROUND_COLOR_VALUE = "BackgroundColorValue";
	public static final String IFD_PIXEL_INTENSITY_RANGE = "PixelIntensityRange";
	public static final String IFD_TRANSPARENCY_INDICATOR = "TransparencyIndicator";
	public static final String IFD_COLOR_CHARACTERIZATION = "ColorCharacterization";
	public static final String IFD_HC_USAGE = "HCUsage";
	public static final String IFD_TRAP_INDICATOR = "TrapIndicator";
	public static final String IFD_CMYK_EQUIVALENT = "CMYKEquivalent";
	public static final String IFD_SEM_INFO = "SEMInfo";
	public static final String IFD_AFCP_IPTC = "AFCP_IPTC";
	public static final String IFD_PIXEL_MAGIC_JBIG_OPTIONS = "PixelMagicJBIGOptions";
	public static final String IFD_JPL_CARTO_IFD = "JPLCartoIFD";
	public static final String IFD_MODEL_TRANSFORM = "ModelTransform";
	public static final String IFD_WB_GRGB_LEVELS = "WB_GRGBLevels";
	public static final String IFD_LEAF_DATA = "LeafData";
	public static final String IFD_PHOTOSHOP_SETTINGS = "PhotoshopSettings";
	public static final String IFD_EXIF_OFFSET = "ExifOffset";
	public static final String IFD_ICC_PROFILE = "ICC_Profile";
	public static final String IFD_TIFF_FX_EXTENSIONS = "TIFF_FXExtensions";
	public static final String IFD_MULTI_PROFILES = "MultiProfiles";
	public static final String IFD_SHARED_DATA = "SharedData";
	public static final String IFD_T88_OPTIONS = "T88Options";
	public static final String IFD_IMAGE_LAYER = "ImageLayer";
	public static final String IFD_GEO_TIFF_DIRECTORY = "GeoTiffDirectory";
	public static final String IFD_GEO_TIFF_DOUBLE_PARAMS = "GeoTiffDoubleParams";
	public static final String IFD_GEO_TIFF_ASCII_PARAMS = "GeoTiffAsciiParams";
	public static final String IFD_JBIG_OPTIONS = "JBIGOptions";
	public static final String IFD_EXPOSURE_PROGRAM = "ExposureProgram";
	public static final String IFD_SPECTRAL_SENSITIVITY = "SpectralSensitivity";
	public static final String IFD_GPS_INFO = "GPSInfo";
	public static final String IFD_ISO = "ISO";
	public static final String IFD_OPTO_ELECTRIC_CONV_FACTOR = "Opto-ElectricConvFactor";
	public static final String IFD_INTERLACE = "Interlace";
	public static final String IFD_TIME_ZONE_OFFSET = "TimeZoneOffset";
	public static final String IFD_SELF_TIMER_MODE = "SelfTimerMode";
	public static final String IFD_SENSITIVITY_TYPE = "SensitivityType";
	public static final String IFD_STANDARD_OUTPUT_SENSITIVITY = "StandardOutputSensitivity";
	public static final String IFD_RECOMMENDED_EXPOSURE_INDEX = "RecommendedExposureIndex";
	public static final String IFD_ISO_SPEED = "ISOSpeed";
	public static final String IFD_ISO_SPEED_LATITUDEYYY = "ISOSpeedLatitudeyyy";
	public static final String IFD_ISO_SPEED_LATITUDEZZZ = "ISOSpeedLatitudezzz";
	public static final String IFD_FAX_RECV_PARAMS = "FaxRecvParams";
	public static final String IFD_FAX_SUB_ADDRESS = "FaxSubAddress";
	public static final String IFD_FAX_RECV_TIME = "FaxRecvTime";
	public static final String IFD_FEDEX_EDR = "FedexEDR";
	public static final String IFD_LEAF_SUB_IFD = "LeafSubIFD";
	public static final String IFD_EXIF_VERSION = "ExifVersion";
	public static final String IFD_DATE_TIME_ORIGINAL = "DateTimeOriginal";
	public static final String IFD_CREATE_DATE = "CreateDate";
	public static final String IFD_GOOGLE_PLUS_UPLOAD_CODE = "GooglePlusUploadCode";
	public static final String IFD_COMPONENTS_CONFIGURATION = "ComponentsConfiguration";
	public static final String IFD_COMPRESSED_BITS_PER_PIXEL = "CompressedBitsPerPixel";
	public static final String IFD_SHUTTER_SPEED_VALUE = "ShutterSpeedValue";
	public static final String IFD_APERTURE_VALUE = "ApertureValue";
	public static final String IFD_BRIGHTNESS_VALUE = "BrightnessValue";
	public static final String IFD_EXPOSURE_COMPENSATION = "ExposureCompensation";
	public static final String IFD_MAX_APERTURE_VALUE = "MaxApertureValue";
	public static final String IFD_SUBJECT_DISTANCE = "SubjectDistance";
	public static final String IFD_METERING_MODE = "MeteringMode";
	public static final String IFD_LIGHT_SOURCE = "LightSource";
	public static final String IFD_FLASH = "Flash";
	public static final String IFD_FOCAL_LENGTH = "FocalLength";
	public static final String IFD_FLASH_ENERGY = "FlashEnergy";
	public static final String IFD_SPATIAL_FREQUENCY_RESPONSE = "SpatialFrequencyResponse";
	public static final String IFD_NOISE = "Noise";
	public static final String IFD_FOCAL_PLANE_X_RESOLUTION = "FocalPlaneXResolution";
	public static final String IFD_FOCAL_PLANE_Y_RESOLUTION = "FocalPlaneYResolution";
	public static final String IFD_FOCAL_PLANE_RESOLUTION_UNIT = "FocalPlaneResolutionUnit";
	public static final String IFD_IMAGE_NUMBER = "ImageNumber";
	public static final String IFD_SECURITY_CLASSIFICATION = "SecurityClassification";
	public static final String IFD_IMAGE_HISTORY = "ImageHistory";
	public static final String IFD_SUBJECT_AREA = "SubjectArea";
	public static final String IFD_EXPOSURE_INDEX = "ExposureIndex";
	public static final String IFD_TIFF_EP_STANDARD_ID = "TIFF-EPStandardID";
	public static final String IFD_SENSING_METHOD = "SensingMethod";
	public static final String IFD_CIP3_DATA_FILE = "CIP3DataFile";
	public static final String IFD_CIP3_SHEET = "CIP3Sheet";
	public static final String IFD_CIP3_SIDE = "CIP3Side";
	public static final String IFD_STO_NITS = "StoNits";
	public static final String IFD_MAKER_NOTES = "Maker Notes";
	public static final String IFD_USER_COMMENT = "UserComment";
	public static final String IFD_SUB_SEC_TIME = "SubSecTime";
	public static final String IFD_SUB_SEC_TIME_ORIGINAL = "SubSecTimeOriginal";
	public static final String IFD_SUB_SEC_TIME_DIGITIZED = "SubSecTimeDigitized";
	public static final String IFD_MS_DOCUMENT_TEXT = "MSDocumentText";
	public static final String IFD_MS_PROPERTY_SET_STORAGE = "MSPropertySetStorage";
	public static final String IFD_MS_DOCUMENT_TEXT_POSITION = "MSDocumentTextPosition";
	public static final String IFD_IMAGE_SOURCE_DATA = "ImageSourceData";
	public static final String IFD_XP_TITLE = "XPTitle";
	public static final String IFD_XP_COMMENT = "XPComment";
	public static final String IFD_XP_AUTHOR = "XPAuthor";
	public static final String IFD_XP_KEYWORDS = "XPKeywords";
	public static final String IFD_XP_SUBJECT = "XPSubject";
	public static final String IFD_FLASHPIX_VERSION = "FlashpixVersion";
	public static final String IFD_COLOR_SPACE = "ColorSpace";
	public static final String IFD_EXIF_IMAGE_WIDTH = "ExifImageWidth";
	public static final String IFD_EXIF_IMAGE_HEIGHT = "ExifImageHeight";
	public static final String IFD_RELATED_SOUND_FILE = "RelatedSoundFile";
	public static final String IFD_INTEROP_OFFSET = "InteropOffset";
	public static final String IFD_SUBJECT_LOCATION = "SubjectLocation";
	public static final String IFD_FILE_SOURCE = "FileSource";
	public static final String IFD_SCENE_TYPE = "SceneType";
	public static final String IFD_CFA_PATTERN = "CFAPattern";
	public static final String IFD_CUSTOM_RENDERED = "CustomRendered";
	public static final String IFD_EXPOSURE_MODE = "ExposureMode";
	public static final String IFD_WHITE_BALANCE = "WhiteBalance";
	public static final String IFD_DIGITAL_ZOOM_RATIO = "DigitalZoomRatio";
	public static final String IFD_FOCAL_LENGTH_IN35MM_FORMAT = "FocalLengthIn35mmFormat";
	public static final String IFD_SCENE_CAPTURE_TYPE = "SceneCaptureType";
	public static final String IFD_GAIN_CONTROL = "GainControl";
	public static final String IFD_CONTRAST = "Contrast";
	public static final String IFD_SATURATION = "Saturation";
	public static final String IFD_SHARPNESS = "Sharpness";
	public static final String IFD_DEVICE_SETTING_DESCRIPTION = "DeviceSettingDescription";
	public static final String IFD_SUBJECT_DISTANCE_RANGE = "SubjectDistanceRange";
	public static final String IFD_IMAGE_UNIQUE_ID = "ImageUniqueID";
	public static final String IFD_OWNER_NAME = "OwnerName";
	public static final String IFD_SERIAL_NUMBER = "SerialNumber";
	public static final String IFD_LENS_INFO = "LensInfo";
	public static final String IFD_LENS_MAKE = "LensMake";
	public static final String IFD_LENS_MODEL = "LensModel";
	public static final String IFD_LENS_SERIAL_NUMBER = "LensSerialNumber";
	public static final String IFD_G_D_A_L_METADATA = "GDALMetadata";
	public static final String IFD_G_D_A_L_NO_DATA = "GDALNoData";
	public static final String IFD_GAMMA = "Gamma";
	public static final String IFD_EXPAND_SOFTWARE = "ExpandSoftware";
	public static final String IFD_EXPAND_LENS = "ExpandLens";
	public static final String IFD_EXPAND_FILM = "ExpandFilm";
	public static final String IFD_EXPAND_FILTER_LENS = "ExpandFilterLens";
	public static final String IFD_EXPAND_SCANNER = "ExpandScanner";
	public static final String IFD_EXPAND_FLASH_LAMP = "ExpandFlashLamp";
	public static final String IFD_PIXEL_FORMAT = "PixelFormat";
	public static final String IFD_TRANSFORMATION = "Transformation";
	public static final String IFD_UNCOMPRESSED = "Uncompressed";
	public static final String IFD_IMAGE_TYPE = "ImageType";
	public static final String IFD_WIDTH_RESOLUTION = "WidthResolution";
	public static final String IFD_HEIGHT_RESOLUTION = "HeightResolution";
	public static final String IFD_IMAGE_OFFSET = "ImageOffset";
	public static final String IFD_IMAGE_BYTE_COUNT = "ImageByteCount";
	public static final String IFD_ALPHA_OFFSET = "AlphaOffset";
	public static final String IFD_ALPHA_BYTE_COUNT = "AlphaByteCount";
	public static final String IFD_IMAGE_DATA_DISCARD = "ImageDataDiscard";
	public static final String IFD_ALPHA_DATA_DISCARD = "AlphaDataDiscard";
	public static final String IFD_OCE_SCANJOB_DESC = "OceScanjobDesc";
	public static final String IFD_OCE_APPLICATION_SELECTOR = "OceApplicationSelector";
	public static final String IFD_OCE_ID_NUMBER = "OceIDNumber";
	public static final String IFD_OCE_IMAGE_LOGIC = "OceImageLogic";
	public static final String IFD_ANNOTATIONS = "Annotations";
	public static final String IFD_PRINT_IM = "PrintIM";
	public static final String IFD_ORIGINAL_FILE_NAME = "OriginalFileName";
	public static final String IFD_USP_TO_ORIGINAL_CONTENT_TYPE = "USPTOOriginalContentType";
	public static final String IFD_DNG_VERSION = "DNGVersion";
	public static final String IFD_DNG_BACKWARD_VERSION = "DNGBackwardVersion";
	public static final String IFD_UNIQUE_CAMERA_MODEL = "UniqueCameraModel";
	public static final String IFD_LOCALIZED_CAMERA_MODEL = "LocalizedCameraModel";
	public static final String IFD_CFA_PLANE_COLOR = "CFAPlaneColor";
	public static final String IFD_CFA_LAYOUT = "CFALayout";
	public static final String IFD_LINEARIZATION_TABLE = "LinearizationTable";
	public static final String IFD_BLACK_LEVEL_REPEAT_DIM = "BlackLevelRepeatDim";
	public static final String IFD_BLACK_LEVEL = "BlackLevel";
	public static final String IFD_BLACK_LEVEL_DELTA_H = "BlackLevelDeltaH";
	public static final String IFD_BLACK_LEVEL_DELTA_V = "BlackLevelDeltaV";
	public static final String IFD_WHITE_LEVEL = "WhiteLevel";
	public static final String IFD_DEFAULT_SCALE = "DefaultScale";
	public static final String IFD_DEFAULT_CROP_ORIGIN = "DefaultCropOrigin";
	public static final String IFD_DEFAULT_CROP_SIZE = "DefaultCropSize";
	public static final String IFD_COLOR_MATRIX1 = "ColorMatrix1";
	public static final String IFD_COLOR_MATRIX2 = "ColorMatrix2";
	public static final String IFD_CAMERA_CALIBRATION1 = "CameraCalibration1";
	public static final String IFD_CAMERA_CALIBRATION2 = "CameraCalibration2";
	public static final String IFD_REDUCTION_MATRIX1 = "ReductionMatrix1";
	public static final String IFD_REDUCTION_MATRIX2 = "ReductionMatrix2";
	public static final String IFD_ANALOG_BALANCE = "AnalogBalance";
	public static final String IFD_AS_SHOT_NEUTRAL = "AsShotNeutral";
	public static final String IFD_AS_SHOT_WHITE_X_Y = "AsShotWhiteXY";
	public static final String IFD_BASELINE_EXPOSURE = "BaselineExposure";
	public static final String IFD_BASELINE_NOISE = "BaselineNoise";
	public static final String IFD_BASELINE_SHARPNESS = "BaselineSharpness";
	public static final String IFD_BAYER_GREEN_SPLIT = "BayerGreenSplit";
	public static final String IFD_LINEAR_RESPONSE_LIMIT = "LinearResponseLimit";
	public static final String IFD_CAMERA_SERIAL_NUMBER = "CameraSerialNumber";
	public static final String IFD_DNG_LENS_INFO = "DNGLensInfo";
	public static final String IFD_CHROMA_BLUR_RADIUS = "ChromaBlurRadius";
	public static final String IFD_ANTI_ALIAS_STRENGTH = "AntiAliasStrength";
	public static final String IFD_SHADOW_SCALE = "ShadowScale";
	public static final String IFD_PRIVATE_MAKER_NOTES = "Private Maker Notes";
	public static final String IFD_MAKER_NOTE_SAFETY = "MakerNoteSafety";
	public static final String IFD_RAW_IMAGE_SEGMENTATION = "RawImageSegmentation";
	public static final String IFD_CALIBRATION_ILLUMINANT1 = "CalibrationIlluminant1";
	public static final String IFD_CALIBRATION_ILLUMINANT2 = "CalibrationIlluminant2";
	public static final String IFD_BEST_QUALITY_SCALE = "BestQualityScale";
	public static final String IFD_RAW_DATA_UNIQUE_I_D = "RawDataUniqueID";
	public static final String IFD_ALIAS_LAYER_METADATA = "AliasLayerMetadata";
	public static final String IFD_ORIGINAL_RAW_FILE_NAME = "OriginalRawFileName";
	public static final String IFD_ORIGINAL_RAW_FILE_DATA = "OriginalRawFileData";
	public static final String IFD_ACTIVE_AREA = "ActiveArea";
	public static final String IFD_MASKED_AREAS = "MaskedAreas";
	public static final String IFD_AS_SHOT_ICC_PROFILE = "AsShotICCProfile";
	public static final String IFD_AS_SHOT_PRE_PROFILE_MATRIX = "AsShotPreProfileMatrix";
	public static final String IFD_CURRENT_ICC_PROFILE = "CurrentICCProfile";
	public static final String IFD_CURRENT_PRE_PROFILE_MATRIX = "CurrentPreProfileMatrix";
	public static final String IFD_COLORIMETRIC_REFERENCE = "ColorimetricReference";
	public static final String IFD_S_RAW_TYPE = "SRawType";
	public static final String IFD_PANASONIC_TITLE = "PanasonicTitle";
	public static final String IFD_PANASONIC_TITLE2 = "PanasonicTitle2";
	public static final String IFD_CAMERA_CALIBRATION_SIG = "CameraCalibrationSig";
	public static final String IFD_PROFILE_CALIBRATION_SIG = "ProfileCalibrationSig";
	public static final String IFD_PROFILE_IFD = "ProfileIFD";
	public static final String IFD_AS_SHOT_PROFILE_NAME = "AsShotProfileName";
	public static final String IFD_NOISE_REDUCTION_APPLIED = "NoiseReductionApplied";
	public static final String IFD_PROFILE_NAME = "ProfileName";
	public static final String IFD_PROFILE_HUE_SAT_MAP_DIMS = "ProfileHueSatMapDims";
	public static final String IFD_PROFILE_HUE_SAT_MAP_DATA1 = "ProfileHueSatMapData1";
	public static final String IFD_PROFILE_HUE_SAT_MAP_DATA2 = "ProfileHueSatMapData2";
	public static final String IFD_PROFILE_TONE_CURVE = "ProfileToneCurve";
	public static final String IFD_PROFILE_EMBED_POLICY = "ProfileEmbedPolicy";
	public static final String IFD_PROFILE_COPYRIGHT = "ProfileCopyright";
	public static final String IFD_FORWARD_MATRIX1 = "ForwardMatrix1";
	public static final String IFD_FORWARD_MATRIX2 = "ForwardMatrix2";
	public static final String IFD_PREVIEW_APPLICATION_NAME = "PreviewApplicationName";
	public static final String IFD_PREVIEW_APPLICATION_VERSION = "PreviewApplicationVersion";
	public static final String IFD_PREVIEW_SETTINGS_NAME = "PreviewSettingsName";
	public static final String IFD_PREVIEW_SETTINGS_DIGEST = "PreviewSettingsDigest";
	public static final String IFD_PREVIEW_COLOR_SPACE = "PreviewColorSpace";
	public static final String IFD_PREVIEW_DATE_TIME = "PreviewDateTime";
	public static final String IFD_RAW_IMAGE_DIGEST = "RawImageDigest";
	public static final String IFD_ORIGINAL_RAW_FILE_DIGEST = "OriginalRawFileDigest";
	public static final String IFD_SUB_TILE_BLOCK_SIZE = "SubTileBlockSize";
	public static final String IFD_ROW_INTERLEAVE_FACTOR = "RowInterleaveFactor";
	public static final String IFD_PROFILE_LOOK_TABLE_DIMS = "ProfileLookTableDims";
	public static final String IFD_PROFILE_LOOK_TABLE_DATA = "ProfileLookTableData";
	public static final String IFD_OPCODE_LIST1 = "OpcodeList1";
	public static final String IFD_OPCODE_LIST2 = "OpcodeList2";
	public static final String IFD_OPCODE_LIST3 = "OpcodeList3";
	public static final String IFD_NOISE_PROFILE = "NoiseProfile";
	public static final String IFD_TIME_CODES = "TimeCodes";
	public static final String IFD_FRAME_RATE = "FrameRate";
	public static final String IFD_T_STOP = "TStop";
	public static final String IFD_REEL_NAME = "ReelName";
	public static final String IFD_ORIGINAL_DEFAULT_FINAL_SIZE = "OriginalDefaultFinalSize";
	public static final String IFD_ORIGINAL_BEST_QUALITY_SIZE = "OriginalBestQualitySize";
	public static final String IFD_ORIGINAL_DEFAULT_CROP_SIZE = "OriginalDefaultCropSize";
	public static final String IFD_CAMERA_LABEL = "CameraLabel";
	public static final String IFD_PROFILE_HUE_SAT_MAP_ENCODING = "ProfileHueSatMapEncoding";
	public static final String IFD_PROFILE_LOOK_TABLE_ENCODING = "ProfileLookTableEncoding";
	public static final String IFD_BASELINE_EXPOSURE_OFFSET = "BaselineExposureOffset";
	public static final String IFD_DEFAULT_BLACK_RENDER = "DefaultBlackRender";
	public static final String IFD_NEW_RAW_IMAGE_DIGEST = "NewRawImageDigest";
	public static final String IFD_RAW_TO_PREVIEW_GAIN = "RawToPreviewGain";
	public static final String IFD_DEFAULT_USER_CROP = "DefaultUserCrop";
	public static final String IFD_PADDING = "Padding";
	public static final String IFD_OFFSET_SCHEMA = "OffsetSchema";
	public static final String IFD_LENS = "Lens";
	public static final String IFD_KDC_IFD = "KDC_IFD";
	public static final String IFD_RAW_FILE = "RawFile";
	public static final String IFD_CONVERTER = "Converter";
	public static final String IFD_EXPOSURE = "Exposure";
	public static final String IFD_SHADOWS = "Shadows";
	public static final String IFD_BRIGHTNESS = "Brightness";
	public static final String IFD_SMOOTHNESS = "Smoothness";
	public static final String IFD_MOIRE_FILTER = "MoireFilter";
	
	public IFDLookup()
	{
		ENTRY.put(0x0001, IFD_INTEROP_INDEX);
		ENTRY.put(0x0002, IFD_INTEROP_VERSION);
		ENTRY.put(0x000b, IFD_PROCESSING_SOFTWARE);
		ENTRY.put(0x00fe, IFD_SUBFILE_TYPE);
		ENTRY.put(0x00ff, IFD_OLD_SUBFILE_TYPE);
		ENTRY.put(0x0100, IFD_IMAGE_WIDTH);
		ENTRY.put(0x0101, IFD_IMAGE_HEIGHT);
		ENTRY.put(0x0102, IFD_BITS_PER_SAMPLE);
		ENTRY.put(0x0103, IFD_COMPRESSION);
		ENTRY.put(0x0106, IFD_PHOTOMETRIC_INTERPRETATION);
		ENTRY.put(0x0107, IFD_THRESHOLDING);
		ENTRY.put(0x0108, IFD_CELL_WIDTH);
		ENTRY.put(0x0109, IFD_CELL_LENGTH);
		ENTRY.put(0x010a, IFD_FILL_ORDER);
		ENTRY.put(0x010d, IFD_DOCUMENT_NAME);
		ENTRY.put(0x010e, IFD_IMAGE_DESCRIPTION);
		ENTRY.put(0x010f, IFD_MAKE);
		ENTRY.put(0x0110, IFD_MODEL);
		ENTRY.put(0x0111, IFD_STRIP_OFFSETS);
		ENTRY.put(0x0112, IFD_ORIENTATION);
		ENTRY.put(0x0115, IFD_SAMPLES_PER_PIXEL);
		ENTRY.put(0x0116, IFD_ROWS_PER_STRIP);
		ENTRY.put(0x0117, IFD_STRIP_BYTE_COUNTS);
		ENTRY.put(0x0118, IFD_MIN_SAMPLE_VALUE);
		ENTRY.put(0x0119, IFD_MAX_SAMPLE_VALUE);
		ENTRY.put(0x011a, IFD_X_RESOLUTION);
		ENTRY.put(0x011b, IFD_Y_RESOLUTION);
		ENTRY.put(0x011c, IFD_PLANAR_CONFIGURATION);
		ENTRY.put(0x011d, IFD_PAGE_NAME);
		ENTRY.put(0x011e, IFD_X_POSITION);
		ENTRY.put(0x011f, IFD_Y_POSITION);
		ENTRY.put(0x0120, IFD_FREE_OFFSETS);
		ENTRY.put(0x0121, IFD_FREE_BYTE_COUNTS);
		ENTRY.put(0x0122, IFD_GRAY_RESPONSE_UNIT);
		ENTRY.put(0x0123, IFD_GRAY_RESPONSE_CURVE);
		ENTRY.put(0x0124, IFD_T4_OPTIONS);
		ENTRY.put(0x0125, IFD_T6_OPTIONS);
		ENTRY.put(0x0128, IFD_RESOLUTION_UNIT);
		ENTRY.put(0x0129, IFD_PAGE_NUMBER);
		ENTRY.put(0x012c, IFD_COLOR_RESPONSE_UNIT);
		ENTRY.put(0x012d, IFD_TRANSFER_FUNCTION);
		ENTRY.put(0x0131, IFD_SOFTWARE);
		ENTRY.put(0x0132, IFD_MODIFY_DATE);
		ENTRY.put(0x013b, IFD_ARTIST);
		ENTRY.put(0x013c, IFD_HOST_COMPUTER);
		ENTRY.put(0x013d, IFD_PREDICTOR);
		ENTRY.put(0x013e, IFD_WHITE_POINT);
		ENTRY.put(0x013f, IFD_PRIMARY_CHROMATICITIES);
		ENTRY.put(0x0140, IFD_COLOR_MAP);
		ENTRY.put(0x0141, IFD_HALFTONE_HINTS);
		ENTRY.put(0x0142, IFD_TILE_WIDTH);
		ENTRY.put(0x0143, IFD_TILE_LENGTH);
		ENTRY.put(0x0144, IFD_TILE_OFFSETS);
		ENTRY.put(0x0145, IFD_TILE_BYTE_COUNTS);
		ENTRY.put(0x0146, IFD_BAD_FAX_LINES);
		ENTRY.put(0x0147, IFD_CLEAN_FAX_DATA);
		ENTRY.put(0x0148, IFD_CONSECUTIVE_BAD_FAX_LINES);
		ENTRY.put(0x014a, IFD_SUB_IFD);
		ENTRY.put(0x014c, IFD_INK_SET);
		ENTRY.put(0x014d, IFD_INK_NAMES);
		ENTRY.put(0x014e, IFD_NUMBEROF_INKS);
		ENTRY.put(0x0150, IFD_DOT_RANGE);
		ENTRY.put(0x0151, IFD_TARGET_PRINTER);
		ENTRY.put(0x0152, IFD_EXTRA_SAMPLES);
		ENTRY.put(0x0153, IFD_SAMPLE_FORMAT);
		ENTRY.put(0x0154, IFD_S_MIN_SAMPLE_VALUE);
		ENTRY.put(0x0155, IFD_S_MAX_SAMPLE_VALUE);
		ENTRY.put(0x0156, IFD_TRANSFER_RANGE);
		ENTRY.put(0x0157, IFD_CLIP_PATH);
		ENTRY.put(0x0158, IFD_X_CLIP_PATH_UNITS);
		ENTRY.put(0x0159, IFD_Y_CLIP_PATH_UNITS);
		ENTRY.put(0x015a, IFD_INDEXED);
		ENTRY.put(0x015b, IFD_JPEG_TABLES);
		ENTRY.put(0x015f, IFD_OPI_PROXY);
		ENTRY.put(0x0190, IFD_GLOBAL_PARAMETERS_I_F_D);
		ENTRY.put(0x0191, IFD_PROFILE_TYPE);
		ENTRY.put(0x0192, IFD_FAX_PROFILE);
		ENTRY.put(0x0193, IFD_CODING_METHODS);
		ENTRY.put(0x0194, IFD_VERSION_YEAR);
		ENTRY.put(0x0195, IFD_MODE_NUMBER);
		ENTRY.put(0x01b1, IFD_DECODE);
		ENTRY.put(0x01b2, IFD_DEFAULT_IMAGE_COLOR);
		ENTRY.put(0x01b3, IFD_T82_OPTIONS);
		ENTRY.put(0x01b5, IFD_JPEG_TABLES);
		ENTRY.put(0x0200, IFD_JPEG_PROC);
		ENTRY.put(0x0201, IFD_THUMBNAIL_OFFSET);
		ENTRY.put(0x0202, IFD_THUMBNAIL_LENGTH);
		ENTRY.put(0x0203, IFD_JPEG_RESTART_INTERVAL);
		ENTRY.put(0x0205, IFD_JPEG_LOSSLESS_PREDICTORS);
		ENTRY.put(0x0206, IFD_JPEG_POINT_TRANSFORMS);
		ENTRY.put(0x0207, IFD_JPEG_Q_TABLES);
		ENTRY.put(0x0208, IFD_JPEG_DC_TABLES);
		ENTRY.put(0x0209, IFD_JPEG_AC_TABLES);
		ENTRY.put(0x0211, IFD_YCBCR_COEFFICIENTS);
		ENTRY.put(0x0212, IFD_YCBCR_SUB_SAMPLING);
		ENTRY.put(0x0213, IFD_YCBCR_POSITIONING);
		ENTRY.put(0x0214, IFD_REFERENCE_BLACK_WHITE);
		ENTRY.put(0x022f, IFD_STRIP_ROW_COUNTS);
		ENTRY.put(0x02bc, IFD_APPLICATION_NOTES);
		ENTRY.put(0x03e7, IFD_USP_TO_MISCELLANEOUS);
		ENTRY.put(0x1000, IFD_RELATED_IMAGE_FILE_FORMAT);
		ENTRY.put(0x1001, IFD_RELATED_IMAGE_WIDTH);
		ENTRY.put(0x1002, IFD_RELATED_IMAGE_HEIGHT);
		ENTRY.put(0x4746, IFD_RATING);
		ENTRY.put(0x4747, IFD_XP_DIP_XML);
		ENTRY.put(0x4748, IFD_STITCH_INFO);
		ENTRY.put(0x4749, IFD_RATING_PERCENT);
		ENTRY.put(0x7000, IFD_SONY_RAW_FILE_TYPE);
		ENTRY.put(0x7035, IFD_CHROMATIC_ABERRATION_CORR_PARAMS);
		ENTRY.put(0x7037, IFD_DISTORTION_CORR_PARAMS);
		ENTRY.put(0x800d, IFD_IMAGE_ID);
		ENTRY.put(0x80a3, IFD_WANG_TAG1);
		ENTRY.put(0x80a4, IFD_WANG_ANNOTATION);
		ENTRY.put(0x80a5, IFD_WANG_TAG3);
		ENTRY.put(0x80a6, IFD_WANG_TAG4);
		ENTRY.put(0x80b8, IFD_IMAGE_REFERENCE_POINTS);
		ENTRY.put(0x80b9, IFD_REGION_XFORM_TACK_POINT);
		ENTRY.put(0x80ba, IFD_WARP_QUADRILATERAL);
		ENTRY.put(0x80bb, IFD_AFFINE_TRANSFORM_MAT);
		ENTRY.put(0x80e3, IFD_MATTEING);
		ENTRY.put(0x80e4, IFD_DATA_TYPE);
		ENTRY.put(0x80e5, IFD_IMAGE_DEPTH);
		ENTRY.put(0x80e6, IFD_TILE_DEPTH);
		ENTRY.put(0x8214, IFD_IMAGE_FULL_WIDTH);
		ENTRY.put(0x8215, IFD_IMAGE_FULL_HEIGHT);
		ENTRY.put(0x8216, IFD_TEXTURE_FORMAT);
		ENTRY.put(0x8217, IFD_WRAP_MODES);
		ENTRY.put(0x8218, IFD_FOV_COT);
		ENTRY.put(0x8219, IFD_MATRIX_WORLD_TO_SCREEN);
		ENTRY.put(0x821a, IFD_MATRIX_WORLD_TO_CAMERA);
		ENTRY.put(0x827d, IFD_MODEL2);
		ENTRY.put(0x828d, IFD_CFA_REPEAT_PATTERN_DIM);
		ENTRY.put(0x828e, IFD_CFA_PATTERN2);
		ENTRY.put(0x828f, IFD_BATTERY_LEVEL);
		ENTRY.put(0x8290, IFD_KODAK_I_F_D);
		ENTRY.put(0x8298, IFD_COPYRIGHT);
		ENTRY.put(0x829a, IFD_EXPOSURE_TIME);
		ENTRY.put(0x829d, IFD_FNUMBER);
		ENTRY.put(0x82a5, IFD_MD_FILE_TAG);
		ENTRY.put(0x82a6, IFD_MD_SCALE_PIXEL);
		ENTRY.put(0x82a7, IFD_MD_COLOR_TABLE);
		ENTRY.put(0x82a8, IFD_MD_LAB_NAME);
		ENTRY.put(0x82a9, IFD_MD_SAMPLE_INFO);
		ENTRY.put(0x82aa, IFD_MD_PREP_DATE);
		ENTRY.put(0x82ab, IFD_MD_PREP_TIME);
		ENTRY.put(0x82ac, IFD_MD_FILE_UNITS);
		ENTRY.put(0x830e, IFD_PIXEL_SCALE);
		ENTRY.put(0x8335, IFD_ADVENT_SCALE);
		ENTRY.put(0x8336, IFD_ADVENT_REVISION);
		ENTRY.put(0x835c, IFD_UIC1_TAG);
		ENTRY.put(0x835d, IFD_UIC2_TAG);
		ENTRY.put(0x835e, IFD_UIC3_TAG);
		ENTRY.put(0x835f, IFD_UIC4_TAG);
		ENTRY.put(0x83bb, IFD_IPTC_NAA);
		ENTRY.put(0x847e, IFD_INTERGRAPH_PACKET_DATA);
		ENTRY.put(0x847f, IFD_INTERGRAPH_FLAG_REGISTERS);
		ENTRY.put(0x8480, IFD_INTERGRAPH_MATRIX);
		ENTRY.put(0x8481, IFD_INGR_RESERVED);
		ENTRY.put(0x8482, IFD_MODEL_TIE_POINT);
		ENTRY.put(0x84e0, IFD_SITE);
		ENTRY.put(0x84e1, IFD_COLOR_SEQUENCE);
		ENTRY.put(0x84e2, IFD_IT8_HEADER);
		ENTRY.put(0x84e3, IFD_RASTER_PADDING);
		ENTRY.put(0x84e4, IFD_BITS_PER_RUN_LENGTH);
		ENTRY.put(0x84e5, IFD_BITS_PER_EXTENDED_RUN_LENGTH);
		ENTRY.put(0x84e6, IFD_COLOR_TABLE);
		ENTRY.put(0x84e7, IFD_IMAGE_COLOR_INDICATOR);
		ENTRY.put(0x84e8, IFD_BACKGROUND_COLOR_INDICATOR);
		ENTRY.put(0x84e9, IFD_IMAGE_COLOR_VALUE);
		ENTRY.put(0x84ea, IFD_BACKGROUND_COLOR_VALUE);
		ENTRY.put(0x84eb, IFD_PIXEL_INTENSITY_RANGE);
		ENTRY.put(0x84ec, IFD_TRANSPARENCY_INDICATOR);
		ENTRY.put(0x84ed, IFD_COLOR_CHARACTERIZATION);
		ENTRY.put(0x84ee, IFD_HC_USAGE);
		ENTRY.put(0x84ef, IFD_TRAP_INDICATOR);
		ENTRY.put(0x84f0, IFD_CMYK_EQUIVALENT);
		ENTRY.put(0x8546, IFD_SEM_INFO);
		ENTRY.put(0x8568, IFD_AFCP_IPTC);
		ENTRY.put(0x85b8, IFD_PIXEL_MAGIC_JBIG_OPTIONS);
		ENTRY.put(0x85d7, IFD_JPL_CARTO_IFD);
		ENTRY.put(0x85d8, IFD_MODEL_TRANSFORM);
		ENTRY.put(0x8602, IFD_WB_GRGB_LEVELS);
		ENTRY.put(0x8606, IFD_LEAF_DATA);
		ENTRY.put(0x8649, IFD_PHOTOSHOP_SETTINGS);
		ENTRY.put(0x8769, IFD_EXIF_OFFSET);
		ENTRY.put(0x8773, IFD_ICC_PROFILE);
		ENTRY.put(0x877f, IFD_TIFF_FX_EXTENSIONS);
		ENTRY.put(0x8780, IFD_MULTI_PROFILES);
		ENTRY.put(0x8781, IFD_SHARED_DATA);
		ENTRY.put(0x8782, IFD_T88_OPTIONS);
		ENTRY.put(0x87ac, IFD_IMAGE_LAYER);
		ENTRY.put(0x87af, IFD_GEO_TIFF_DIRECTORY);
		ENTRY.put(0x87b0, IFD_GEO_TIFF_DOUBLE_PARAMS);
		ENTRY.put(0x87b1, IFD_GEO_TIFF_ASCII_PARAMS);
		ENTRY.put(0x87be, IFD_JBIG_OPTIONS);
		ENTRY.put(0x8822, IFD_EXPOSURE_PROGRAM);
		ENTRY.put(0x8824, IFD_SPECTRAL_SENSITIVITY);
		ENTRY.put(0x8825, IFD_GPS_INFO);
		ENTRY.put(0x8827, IFD_ISO);
		ENTRY.put(0x8828, IFD_OPTO_ELECTRIC_CONV_FACTOR);
		ENTRY.put(0x8829, IFD_INTERLACE);
		ENTRY.put(0x882a, IFD_TIME_ZONE_OFFSET);
		ENTRY.put(0x882b, IFD_SELF_TIMER_MODE);
		ENTRY.put(0x8830, IFD_SENSITIVITY_TYPE);
		ENTRY.put(0x8831, IFD_STANDARD_OUTPUT_SENSITIVITY);
		ENTRY.put(0x8832, IFD_RECOMMENDED_EXPOSURE_INDEX);
		ENTRY.put(0x8833, IFD_ISO_SPEED);
		ENTRY.put(0x8834, IFD_ISO_SPEED_LATITUDEYYY);
		ENTRY.put(0x8835, IFD_ISO_SPEED_LATITUDEZZZ);
		ENTRY.put(0x885c, IFD_FAX_RECV_PARAMS);
		ENTRY.put(0x885d, IFD_FAX_SUB_ADDRESS);
		ENTRY.put(0x885e, IFD_FAX_RECV_TIME);
		ENTRY.put(0x8871, IFD_FEDEX_EDR);
		ENTRY.put(0x888a, IFD_LEAF_SUB_IFD);
		ENTRY.put(0x9000, IFD_EXIF_VERSION);
		ENTRY.put(0x9003, IFD_DATE_TIME_ORIGINAL);
		ENTRY.put(0x9004, IFD_CREATE_DATE);
		ENTRY.put(0x9009, IFD_GOOGLE_PLUS_UPLOAD_CODE);
		ENTRY.put(0x9101, IFD_COMPONENTS_CONFIGURATION);
		ENTRY.put(0x9102, IFD_COMPRESSED_BITS_PER_PIXEL);
		ENTRY.put(0x9201, IFD_SHUTTER_SPEED_VALUE);
		ENTRY.put(0x9202, IFD_APERTURE_VALUE);
		ENTRY.put(0x9203, IFD_BRIGHTNESS_VALUE);
		ENTRY.put(0x9204, IFD_EXPOSURE_COMPENSATION);
		ENTRY.put(0x9205, IFD_MAX_APERTURE_VALUE);
		ENTRY.put(0x9206, IFD_SUBJECT_DISTANCE);
		ENTRY.put(0x9207, IFD_METERING_MODE);
		ENTRY.put(0x9208, IFD_LIGHT_SOURCE);
		ENTRY.put(0x9209, IFD_FLASH);
		ENTRY.put(0x920a, IFD_FOCAL_LENGTH);
		ENTRY.put(0x920b, IFD_FLASH_ENERGY);
		ENTRY.put(0x920c, IFD_SPATIAL_FREQUENCY_RESPONSE);
		ENTRY.put(0x920d, IFD_NOISE);
		ENTRY.put(0x920e, IFD_FOCAL_PLANE_X_RESOLUTION);
		ENTRY.put(0x920f, IFD_FOCAL_PLANE_Y_RESOLUTION);
		ENTRY.put(0x9210, IFD_FOCAL_PLANE_RESOLUTION_UNIT);
		ENTRY.put(0x9211, IFD_IMAGE_NUMBER);
		ENTRY.put(0x9212, IFD_SECURITY_CLASSIFICATION);
		ENTRY.put(0x9213, IFD_IMAGE_HISTORY);
		ENTRY.put(0x9214, IFD_SUBJECT_AREA);
		ENTRY.put(0x9215, IFD_EXPOSURE_INDEX);
		ENTRY.put(0x9216, IFD_TIFF_EP_STANDARD_ID);
		ENTRY.put(0x9217, IFD_SENSING_METHOD);
		ENTRY.put(0x923a, IFD_CIP3_DATA_FILE);
		ENTRY.put(0x923b, IFD_CIP3_SHEET);
		ENTRY.put(0x923c, IFD_CIP3_SIDE);
		ENTRY.put(0x923f, IFD_STO_NITS);
		ENTRY.put(0x927c, IFD_MAKER_NOTES);
		ENTRY.put(0x9286, IFD_USER_COMMENT);
		ENTRY.put(0x9290, IFD_SUB_SEC_TIME);
		ENTRY.put(0x9291, IFD_SUB_SEC_TIME_ORIGINAL);
		ENTRY.put(0x9292, IFD_SUB_SEC_TIME_DIGITIZED);
		ENTRY.put(0x932f, IFD_MS_DOCUMENT_TEXT);
		ENTRY.put(0x9330, IFD_MS_PROPERTY_SET_STORAGE);
		ENTRY.put(0x9331, IFD_MS_DOCUMENT_TEXT_POSITION);
		ENTRY.put(0x935c, IFD_IMAGE_SOURCE_DATA);
		ENTRY.put(0x9c9b, IFD_XP_TITLE);
		ENTRY.put(0x9c9c, IFD_XP_COMMENT);
		ENTRY.put(0x9c9d, IFD_XP_AUTHOR);
		ENTRY.put(0x9c9e, IFD_XP_KEYWORDS);
		ENTRY.put(0x9c9f, IFD_XP_SUBJECT);
		ENTRY.put(0xa000, IFD_FLASHPIX_VERSION);
		ENTRY.put(0xa001, IFD_COLOR_SPACE);
		ENTRY.put(0xa002, IFD_EXIF_IMAGE_WIDTH);
		ENTRY.put(0xa003, IFD_EXIF_IMAGE_HEIGHT);
		ENTRY.put(0xa004, IFD_RELATED_SOUND_FILE);
		ENTRY.put(0xa005, IFD_INTEROP_OFFSET);
		ENTRY.put(0xa20b, IFD_FLASH_ENERGY);
		ENTRY.put(0xa20c, IFD_SPATIAL_FREQUENCY_RESPONSE);
		ENTRY.put(0xa20d, IFD_NOISE);
		ENTRY.put(0xa20e, IFD_FOCAL_PLANE_X_RESOLUTION);
		ENTRY.put(0xa20f, IFD_FOCAL_PLANE_Y_RESOLUTION);
		ENTRY.put(0xa210, IFD_FOCAL_PLANE_RESOLUTION_UNIT);
		ENTRY.put(0xa211, IFD_IMAGE_NUMBER);
		ENTRY.put(0xa212, IFD_SECURITY_CLASSIFICATION);
		ENTRY.put(0xa213, IFD_IMAGE_HISTORY);
		ENTRY.put(0xa214, IFD_SUBJECT_LOCATION);
		ENTRY.put(0xa215, IFD_EXPOSURE_INDEX);
		ENTRY.put(0xa216, IFD_TIFF_EP_STANDARD_ID);
		ENTRY.put(0xa217, IFD_SENSING_METHOD);
		ENTRY.put(0xa300, IFD_FILE_SOURCE);
		ENTRY.put(0xa301, IFD_SCENE_TYPE);
		ENTRY.put(0xa302, IFD_CFA_PATTERN);
		ENTRY.put(0xa401, IFD_CUSTOM_RENDERED);
		ENTRY.put(0xa402, IFD_EXPOSURE_MODE);
		ENTRY.put(0xa403, IFD_WHITE_BALANCE);
		ENTRY.put(0xa404, IFD_DIGITAL_ZOOM_RATIO);
		ENTRY.put(0xa405, IFD_FOCAL_LENGTH_IN35MM_FORMAT);
		ENTRY.put(0xa406, IFD_SCENE_CAPTURE_TYPE);
		ENTRY.put(0xa407, IFD_GAIN_CONTROL);
		ENTRY.put(0xa408, IFD_CONTRAST);
		ENTRY.put(0xa409, IFD_SATURATION);
		ENTRY.put(0xa40a, IFD_SHARPNESS);
		ENTRY.put(0xa40b, IFD_DEVICE_SETTING_DESCRIPTION);
		ENTRY.put(0xa40c, IFD_SUBJECT_DISTANCE_RANGE);
		ENTRY.put(0xa420, IFD_IMAGE_UNIQUE_ID);
		ENTRY.put(0xa430, IFD_OWNER_NAME);
		ENTRY.put(0xa431, IFD_SERIAL_NUMBER);
		ENTRY.put(0xa432, IFD_LENS_INFO);
		ENTRY.put(0xa433, IFD_LENS_MAKE);
		ENTRY.put(0xa434, IFD_LENS_MODEL);
		ENTRY.put(0xa435, IFD_LENS_SERIAL_NUMBER);
		ENTRY.put(0xa480, IFD_G_D_A_L_METADATA);
		ENTRY.put(0xa481, IFD_G_D_A_L_NO_DATA);
		ENTRY.put(0xa500, IFD_GAMMA);
		ENTRY.put(0xafc0, IFD_EXPAND_SOFTWARE);
		ENTRY.put(0xafc1, IFD_EXPAND_LENS);
		ENTRY.put(0xafc2, IFD_EXPAND_FILM);
		ENTRY.put(0xafc3, IFD_EXPAND_FILTER_LENS);
		ENTRY.put(0xafc4, IFD_EXPAND_SCANNER);
		ENTRY.put(0xafc5, IFD_EXPAND_FLASH_LAMP);
		ENTRY.put(0xbc01, IFD_PIXEL_FORMAT);
		ENTRY.put(0xbc02, IFD_TRANSFORMATION);
		ENTRY.put(0xbc03, IFD_UNCOMPRESSED);
		ENTRY.put(0xbc04, IFD_IMAGE_TYPE);
		ENTRY.put(0xbc80, IFD_IMAGE_WIDTH);
		ENTRY.put(0xbc81, IFD_IMAGE_HEIGHT);
		ENTRY.put(0xbc82, IFD_WIDTH_RESOLUTION);
		ENTRY.put(0xbc83, IFD_HEIGHT_RESOLUTION);
		ENTRY.put(0xbcc0, IFD_IMAGE_OFFSET);
		ENTRY.put(0xbcc1, IFD_IMAGE_BYTE_COUNT);
		ENTRY.put(0xbcc2, IFD_ALPHA_OFFSET);
		ENTRY.put(0xbcc3, IFD_ALPHA_BYTE_COUNT);
		ENTRY.put(0xbcc4, IFD_IMAGE_DATA_DISCARD);
		ENTRY.put(0xbcc5, IFD_ALPHA_DATA_DISCARD);
		ENTRY.put(0xc427, IFD_OCE_SCANJOB_DESC);
		ENTRY.put(0xc428, IFD_OCE_APPLICATION_SELECTOR);
		ENTRY.put(0xc429, IFD_OCE_ID_NUMBER);
		ENTRY.put(0xc42a, IFD_OCE_IMAGE_LOGIC);
		ENTRY.put(0xc44f, IFD_ANNOTATIONS);
		ENTRY.put(0xc4a5, IFD_PRINT_IM);
		ENTRY.put(0xc573, IFD_ORIGINAL_FILE_NAME);
		ENTRY.put(0xc580, IFD_USP_TO_ORIGINAL_CONTENT_TYPE);
		ENTRY.put(0xc612, IFD_DNG_VERSION);
		ENTRY.put(0xc613, IFD_DNG_BACKWARD_VERSION);
		ENTRY.put(0xc614, IFD_UNIQUE_CAMERA_MODEL);
		ENTRY.put(0xc615, IFD_LOCALIZED_CAMERA_MODEL);
		ENTRY.put(0xc616, IFD_CFA_PLANE_COLOR);
		ENTRY.put(0xc617, IFD_CFA_LAYOUT);
		ENTRY.put(0xc618, IFD_LINEARIZATION_TABLE);
		ENTRY.put(0xc619, IFD_BLACK_LEVEL_REPEAT_DIM);
		ENTRY.put(0xc61a, IFD_BLACK_LEVEL);
		ENTRY.put(0xc61b, IFD_BLACK_LEVEL_DELTA_H);
		ENTRY.put(0xc61c, IFD_BLACK_LEVEL_DELTA_V);
		ENTRY.put(0xc61d, IFD_WHITE_LEVEL);
		ENTRY.put(0xc61e, IFD_DEFAULT_SCALE);
		ENTRY.put(0xc61f, IFD_DEFAULT_CROP_ORIGIN);
		ENTRY.put(0xc620, IFD_DEFAULT_CROP_SIZE);
		ENTRY.put(0xc621, IFD_COLOR_MATRIX1);
		ENTRY.put(0xc622, IFD_COLOR_MATRIX2);
		ENTRY.put(0xc623, IFD_CAMERA_CALIBRATION1);
		ENTRY.put(0xc624, IFD_CAMERA_CALIBRATION2);
		ENTRY.put(0xc625, IFD_REDUCTION_MATRIX1);
		ENTRY.put(0xc626, IFD_REDUCTION_MATRIX2);
		ENTRY.put(0xc627, IFD_ANALOG_BALANCE);
		ENTRY.put(0xc628, IFD_AS_SHOT_NEUTRAL);
		ENTRY.put(0xc629, IFD_AS_SHOT_WHITE_X_Y);
		ENTRY.put(0xc62a, IFD_BASELINE_EXPOSURE);
		ENTRY.put(0xc62b, IFD_BASELINE_NOISE);
		ENTRY.put(0xc62c, IFD_BASELINE_SHARPNESS);
		ENTRY.put(0xc62d, IFD_BAYER_GREEN_SPLIT);
		ENTRY.put(0xc62e, IFD_LINEAR_RESPONSE_LIMIT);
		ENTRY.put(0xc62f, IFD_CAMERA_SERIAL_NUMBER);
		ENTRY.put(0xc630, IFD_DNG_LENS_INFO);
		ENTRY.put(0xc631, IFD_CHROMA_BLUR_RADIUS);
		ENTRY.put(0xc632, IFD_ANTI_ALIAS_STRENGTH);
		ENTRY.put(0xc633, IFD_SHADOW_SCALE);
		ENTRY.put(0xc634, IFD_PRIVATE_MAKER_NOTES);
		ENTRY.put(0xc635, IFD_MAKER_NOTE_SAFETY);
		ENTRY.put(0xc640, IFD_RAW_IMAGE_SEGMENTATION);
		ENTRY.put(0xc65a, IFD_CALIBRATION_ILLUMINANT1);
		ENTRY.put(0xc65b, IFD_CALIBRATION_ILLUMINANT2);
		ENTRY.put(0xc65c, IFD_BEST_QUALITY_SCALE);
		ENTRY.put(0xc65d, IFD_RAW_DATA_UNIQUE_I_D);
		ENTRY.put(0xc660, IFD_ALIAS_LAYER_METADATA);
		ENTRY.put(0xc68b, IFD_ORIGINAL_RAW_FILE_NAME);
		ENTRY.put(0xc68c, IFD_ORIGINAL_RAW_FILE_DATA);
		ENTRY.put(0xc68d, IFD_ACTIVE_AREA);
		ENTRY.put(0xc68e, IFD_MASKED_AREAS);
		ENTRY.put(0xc68f, IFD_AS_SHOT_ICC_PROFILE);
		ENTRY.put(0xc690, IFD_AS_SHOT_PRE_PROFILE_MATRIX);
		ENTRY.put(0xc691, IFD_CURRENT_ICC_PROFILE);
		ENTRY.put(0xc692, IFD_CURRENT_PRE_PROFILE_MATRIX);
		ENTRY.put(0xc6bf, IFD_COLORIMETRIC_REFERENCE);
		ENTRY.put(0xc6c5, IFD_S_RAW_TYPE);
		ENTRY.put(0xc6d2, IFD_PANASONIC_TITLE);
		ENTRY.put(0xc6d3, IFD_PANASONIC_TITLE2);
		ENTRY.put(0xc6f3, IFD_CAMERA_CALIBRATION_SIG);
		ENTRY.put(0xc6f4, IFD_PROFILE_CALIBRATION_SIG);
		ENTRY.put(0xc6f5, IFD_PROFILE_IFD);
		ENTRY.put(0xc6f6, IFD_AS_SHOT_PROFILE_NAME);
		ENTRY.put(0xc6f7, IFD_NOISE_REDUCTION_APPLIED);
		ENTRY.put(0xc6f8, IFD_PROFILE_NAME);
		ENTRY.put(0xc6f9, IFD_PROFILE_HUE_SAT_MAP_DIMS);
		ENTRY.put(0xc6fa, IFD_PROFILE_HUE_SAT_MAP_DATA1);
		ENTRY.put(0xc6fb, IFD_PROFILE_HUE_SAT_MAP_DATA2);
		ENTRY.put(0xc6fc, IFD_PROFILE_TONE_CURVE);
		ENTRY.put(0xc6fd, IFD_PROFILE_EMBED_POLICY);
		ENTRY.put(0xc6fe, IFD_PROFILE_COPYRIGHT);
		ENTRY.put(0xc714, IFD_FORWARD_MATRIX1);
		ENTRY.put(0xc715, IFD_FORWARD_MATRIX2);
		ENTRY.put(0xc716, IFD_PREVIEW_APPLICATION_NAME);
		ENTRY.put(0xc717, IFD_PREVIEW_APPLICATION_VERSION);
		ENTRY.put(0xc718, IFD_PREVIEW_SETTINGS_NAME);
		ENTRY.put(0xc719, IFD_PREVIEW_SETTINGS_DIGEST);
		ENTRY.put(0xc71a, IFD_PREVIEW_COLOR_SPACE);
		ENTRY.put(0xc71b, IFD_PREVIEW_DATE_TIME);
		ENTRY.put(0xc71c, IFD_RAW_IMAGE_DIGEST);
		ENTRY.put(0xc71d, IFD_ORIGINAL_RAW_FILE_DIGEST);
		ENTRY.put(0xc71e, IFD_SUB_TILE_BLOCK_SIZE);
		ENTRY.put(0xc71f, IFD_ROW_INTERLEAVE_FACTOR);
		ENTRY.put(0xc725, IFD_PROFILE_LOOK_TABLE_DIMS);
		ENTRY.put(0xc726, IFD_PROFILE_LOOK_TABLE_DATA);
		ENTRY.put(0xc740, IFD_OPCODE_LIST1);
		ENTRY.put(0xc741, IFD_OPCODE_LIST2);
		ENTRY.put(0xc74e, IFD_OPCODE_LIST3);
		ENTRY.put(0xc761, IFD_NOISE_PROFILE);
		ENTRY.put(0xc763, IFD_TIME_CODES);
		ENTRY.put(0xc764, IFD_FRAME_RATE);
		ENTRY.put(0xc772, IFD_T_STOP);
		ENTRY.put(0xc789, IFD_REEL_NAME);
		ENTRY.put(0xc791, IFD_ORIGINAL_DEFAULT_FINAL_SIZE);
		ENTRY.put(0xc792, IFD_ORIGINAL_BEST_QUALITY_SIZE);
		ENTRY.put(0xc793, IFD_ORIGINAL_DEFAULT_CROP_SIZE);
		ENTRY.put(0xc7a1, IFD_CAMERA_LABEL);
		ENTRY.put(0xc7a3, IFD_PROFILE_HUE_SAT_MAP_ENCODING);
		ENTRY.put(0xc7a4, IFD_PROFILE_LOOK_TABLE_ENCODING);
		ENTRY.put(0xc7a5, IFD_BASELINE_EXPOSURE_OFFSET);
		ENTRY.put(0xc7a6, IFD_DEFAULT_BLACK_RENDER);
		ENTRY.put(0xc7a7, IFD_NEW_RAW_IMAGE_DIGEST);
		ENTRY.put(0xc7a8, IFD_RAW_TO_PREVIEW_GAIN);
		ENTRY.put(0xc7b5, IFD_DEFAULT_USER_CROP);
		ENTRY.put(0xea1c, IFD_PADDING);
		ENTRY.put(0xea1d, IFD_OFFSET_SCHEMA);
		ENTRY.put(0xfde8, IFD_OWNER_NAME);
		ENTRY.put(0xfde9, IFD_SERIAL_NUMBER);
		ENTRY.put(0xfdea, IFD_LENS);
		ENTRY.put(0xfe00, IFD_KDC_IFD);
		ENTRY.put(0xfe4c, IFD_RAW_FILE);
		ENTRY.put(0xfe4d, IFD_CONVERTER);
		ENTRY.put(0xfe4e, IFD_WHITE_BALANCE);
		ENTRY.put(0xfe51, IFD_EXPOSURE);
		ENTRY.put(0xfe52, IFD_SHADOWS);
		ENTRY.put(0xfe53, IFD_BRIGHTNESS);
		ENTRY.put(0xfe54, IFD_CONTRAST);
		ENTRY.put(0xfe55, IFD_SATURATION);
		ENTRY.put(0xfe56, IFD_SHARPNESS);
		ENTRY.put(0xfe57, IFD_SMOOTHNESS);
		ENTRY.put(0xfe58, IFD_MOIRE_FILTER);
	}
}
